### ISSUE TITLE
What tool is used to generate XMLs of ASTs?

### ISSUE THREAD

**Issue by Apraso** [phamsonit/freqtals#1]
When FREQTALS is applied to a new collection of Java source code, the first step is to translate Java source files into XML files representing ASTs, and there must be some mechanism to complete the task. The format of the XML files may be specific, as in sample files:
``` xml
<name ColNr="7" EndColNr="14" EndLineNr="3" ID="88" LineNr="3">
  <SimpleName ColNr="12" EndColNr="14" EndLineNr="3" ID="143" LineNr="3">
    <identifier ColNr="12" EndColNr="14" EndLineNr="3" ID="144" LineNr="3">awt</identifier>
    <var ColNr="12" EndColNr="14" EndLineNr="3" ID="145" LineNr="3">false</var>
  </SimpleName>
</name>
```

**Comment by phamsonit** [comment]
We created a tool, named java-importer.jar, to parse java source code to XML. Unfortunately, I am not an author of this tool.
Could you please contact prof. Coen De Roover at VUB Coen.De.Roover@vub.be to get more information about this tool?

**Comment by Apraso** [comment]
Thanks, "java-importer.jar" has been found on another repo "freqtals_demo".
