### ISSUE TITLE
What tool is used to generate XMLs of ASTs of python language?

### ISSUE THREAD

**Issue by XiaoXiaoYi123** [phamsonit/freqtals#2]
When FREQTALS is applied to a new collection of python source code, the first step is to translate python source files into XML files representing ASTs, and there must be some mechanism to complete the task. 
![image](https://user-images.githubusercontent.com/45426458/204726108-2da8d772-9aea-4e1d-9efe-760726e38531.png)

**Comment by phamsonit** [comment]
These are tools for 

1. generating XML from python

https://github.com/phamsonit/INTIMALS_pythonParser

2. converting XML to AST
https://github.com/phamsonit/INTIMALS_pythonConverter

3. Showing the results
https://github.com/phamsonit/INTIMALS_htmlViewer

**Comment by XiaoXiaoYi123** [comment]
Thanks a lot
